config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'cuisines#index'

  get 'cuisines/index'
  get 'cuisines/:id' => 'cuisines#show', as: 'cuisines_show'
  post 'cuisines/:id' => 'cuisines#add', as: 'cuisines_add'
  get 'cuisines_clear' => 'cuisines#clear', as: 'cuisines_clear'

  devise_for :users

  

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :foods
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :cuisine
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :session_cart

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def logged_in_user
    unless user_signed_in?
      flash[:danger] = 'Please log in'
      redirect_to new_user_session_path
    end
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  def session_cart
    if session[:order].nil? or session[:order].empty?
      session[:order] = []
    end
  end

end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def index
    @cuisines = Cuisine.all

  end

  def show
    @cuisine = Cuisine.find(params[:id])
    @food = Food.all
  end

  def add
    @cuisine = Cuisine.find(params[:id])
    :session_cart

    params[:cart].each do |key, value|
      if value.to_i >= 1
        session[:order]<< {key => value.to_i}
      end
    end

    redirect_to cuisines_show_path(@cuisine)
  end

  def clear
    session[:order] = []
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/views/cuisines/index.html.erb
<h1>Restaurants</h1>


<div class="row">
  <% @cuisines.each do |cuisine| %>
      <div class="col-md-3">
        <h3>
          <%= link_to cuisine.title, cuisines_show_path(cuisine.id) %> <br/>
        </h3>
        <%= image_tag cuisine.image.url(:thumb) %> <br/>
      </div>
  <% end %>
</div>

app/views/cuisines/show.html.erb
<div class="media">
  <div class="media-left">
    <%= image_tag @cuisine.image.url(:thumb) %>
  </div>
  <div class="media-body">
    <h3> <%= @cuisine.title.capitalize %>  </h3>

    <%= @cuisine.description %>

  </div>
</div>
<br/>

<%= form_for :cart, :url => { :action => 'add' } do |f| %>
<table class="table table-striped">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity:</th>
      </tr>

      <% counter = 0 %>
      <% @cuisine.foods.each do |food| %>
          <tr>
            <% counter += 1 %>
            <td><%= food.id %> </td>
            <td><%= food.title %></td>
            <td><%= food.description %></td>
            <td><%= food.price %></td>
            <td>
              <%= f.select food.id, (0..10) %>
            </td>
          </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>
      <% end %>
      <%= f.submit 'Add to cart', class: 'btn btn-primary btn-sm' %>
        </td>
      </tr>
</table>
<% end %>

<div class="row">
  <div class="col-md-3">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><h3>In your cart: </h3></h3>
      </div>
      <div class="panel-body">
          <table class="table table-striped">
            <tr>
              <th>Title</th>
              <th>Quantity</th>
            </tr>
            <% session[:order].each do |cart_food| %>
                <% cart_food.each do |key, val| %>
                    <% @food.each do |food| %>
                        <% if food.id == key.to_i %>
                        <tr>
                          <td>
                            <%= food.title %>
                          </td>
                          <td><%= val %></td>
                        </tr>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
          </table>
        <%= link_to 'clear cart', cuisines_clear_path, class: 'btn btn-danger btn-sm' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foods</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin/navbar' %>

<div class="container">
  <div class="jumbotron">

    <%= yield %>

  </div>

</div>


</body>
</html>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Restaurants', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li><a href="#">View orders</a></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foods</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/application/navbar' %>

<div class="container">
  <div class="jumbotron">


      <% flash.each do |type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{type}" %>
      <% end %>

      <%= yield %>


  </div>

</div>


</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Restaurants', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="navbar-nav navbar-right">
          <% if user_signed_in? %>
              <p class="navbar-text">
                Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
              </p>
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% if current_user.admin? %>
                        <li><%= link_to 'Admin Panel', admin_root_path %></li>
                    <% end %>
                    <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                    <li><a href="#">View orders</a></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              </ul>
          <% else %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
              <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
          <% end %>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>